steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/civic-pulsar-499104-p6/my-docker-repo:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/civic-pulsar-499104-p6/my-docker-repo:$COMMIT_SHA']

images:
  - 'us-central1-docker.pkg.dev/civic-pulsar-499104-p6/my-docker-repo:$COMMIT_SHA'
